services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: notes
      POSTGRES_PASSWORD: notes
      POSTGRES_DB: notes
    ports: ["5433:5432"]
    volumes: [notes_pg_data:/var/lib/postgresql/data]

volumes:
  notes_pg_data:
